<#
.SYNOPSIS
  Installs Note Web Vim IME Companion Native Host and registers it with Chrome / Edge.

.DESCRIPTION
  Deploys note-web-ime.exe to %LOCALAPPDATA%\NoteWeb\Companion, writes the Native Messaging
  host manifest JSON with the provided extension ID, and registers the HKCU registry key.

.PARAMETER Browser
  The browser to register the native messaging host for ('Edge' or 'Chrome'). Defaults to 'Edge'.

.PARAMETER ExtensionId
  The extension ID generated by Chrome/Edge when loading the unpacked companion extension.

.PARAMETER ExecutablePath
  Optional path to the compiled note-web-ime.exe. Defaults to companion/windows-host/target/release/note-web-ime.exe.

.EXAMPLE
  .\scripts\install-vim-companion.ps1 -Browser Edge -ExtensionId abcdefghijklmnop
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [ValidateSet("Edge", "Chrome")]
    [string]$Browser = "Edge",

    [Parameter(Mandatory = $true)]
    [string]$ExtensionId,

    [Parameter(Mandatory = $false)]
    [string]$ExecutablePath = ""
)

$ErrorActionPreference = "Stop"

# Unconditionally initialize script directory and repository root
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir

# Sanitize and validate Extension ID
$cleanExtensionId = $ExtensionId.Trim()
if ($cleanExtensionId -match "^chrome-extension://([^/]+)") {
    $cleanExtensionId = $Matches[1]
}
$cleanExtensionId = $cleanExtensionId.TrimEnd("/").Trim()

if (-not ($cleanExtensionId -match "^[a-zA-Z0-9]{16,64}$")) {
    Write-Error "Invalid ExtensionId format: '$ExtensionId'. Extension ID should be an alphanumeric string (e.g. 32 characters)."
    exit 1
}

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " Note Web Vim IME Companion — Windows Host Installer" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# 1. Resolve Executable Path
if ([string]::IsNullOrWhiteSpace($ExecutablePath)) {
    $ExecutablePath = Join-Path $repoRoot "companion\windows-host\target\release\note-web-ime.exe"
}

if (-not (Test-Path $ExecutablePath)) {
    Write-Host "[BUILD] note-web-ime.exe not found at '$ExecutablePath'. Attempting cargo build --release..." -ForegroundColor Yellow
    $windowsHostDir = Join-Path $repoRoot "companion\windows-host"
    Push-Location $windowsHostDir
    try {
        cargo build --release
    }
    finally {
        Pop-Location
    }
}

if (-not (Test-Path $ExecutablePath)) {
    Write-Error "Could not find or build note-web-ime.exe at '$ExecutablePath'."
    exit 1
}

# 2. Setup Target Directory
$installDir = Join-Path $env:LOCALAPPDATA "NoteWeb\Companion"
if (-not (Test-Path $installDir)) {
    New-Item -ItemType Directory -Path $installDir -Force | Out-Null
    Write-Host "[CREATED] Install directory: $installDir" -ForegroundColor Green
}

$destExePath = Join-Path $installDir "note-web-ime.exe"
Copy-Item -Path $ExecutablePath -Destination $destExePath -Force
Write-Host "[DEPLOYED] Native Host binary: $destExePath" -ForegroundColor Green

# 3. Generate Native Messaging Host Manifest
$manifestPath = Join-Path $installDir "com.noteweb.ime.json"
$allowedOrigin = "chrome-extension://$cleanExtensionId/"

$manifestObj = [ordered]@{
    name            = "com.noteweb.ime"
    description     = "Note Web Vim IME Companion Native Host"
    path            = $destExePath
    type            = "stdio"
    allowed_origins = @($allowedOrigin)
}

$manifestJson = $manifestObj | ConvertTo-Json -Depth 4
[System.IO.File]::WriteAllText($manifestPath, $manifestJson, [System.Text.Encoding]::UTF8)
Write-Host "[CREATED] Native Host Manifest: $manifestPath" -ForegroundColor Green
Write-Host "          Allowed Origin: $allowedOrigin" -ForegroundColor Gray

# 4. Register in Windows Registry (HKCU)
$regBase = if ($Browser -eq "Edge") {
    "HKCU:\Software\Microsoft\Edge\NativeMessagingHosts\com.noteweb.ime"
} else {
    "HKCU:\Software\Google\Chrome\NativeMessagingHosts\com.noteweb.ime"
}

if (-not (Test-Path $regBase)) {
    New-Item -Path $regBase -Force | Out-Null
}

Set-ItemProperty -Path $regBase -Name "(Default)" -Value $manifestPath -Force
Write-Host "[REGISTERED] $Browser Native Messaging Host: $regBase" -ForegroundColor Green

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " Installation Successful!" -ForegroundColor Green
Write-Host " Next Steps:" -ForegroundColor White
Write-Host " 1. Reload the extension in your browser ($Browser -> Extensions -> Developer mode -> Refresh)"
Write-Host " 2. Open Note Web in $Browser and enter Vim mode"
Write-Host " 3. Verify status indicator displays: VIM · IME Auto"
Write-Host "============================================================" -ForegroundColor Cyan
